### PR TITLE
fix: compile archived drafts once a week

### PR DESCRIPTION
**Pull request by richardzilincikPantheon**

### CODE REVIEW

**Comment by SlavomirMazurPantheon** [comment]
When the script compiles all archive modules (each Saturday), their `compilation-result` will also be written to the file `IETFDraftYANGPageCompilation.html` and `IETFDraft.json`.
Maybe there should be some flag/condition which will specify that results do not need to be stored into JSON/HTML file. We just need to compile them and store compilation-result into individual HTML files.

**Comment by richardzilincikPantheon** [comment]
It wouldn't be a problem to not overwrite the aggregate HTML file, but the JSON file generated is also used as a cache on the next run. Assuming nobody is manually inspecting the JSON files (they are massive even without the archived drafts) would it be okay to keep the archived draft modules there?

**Comment by SlavomirMazurPantheon** [comment]
Maybe they can be archived here. However, aren't they used for generating HTML?

**Comment by richardzilincikPantheon** [comment]
The HTML is currently generated directly from the same data as the JSON is. But I realized that the cache gets thrown away anyway on the next non-archive run of the script. I'll store the cache for archived drafts in a `IETFDraftArchive.json` file instead.

**Review by SlavomirMazurPantheon — APPROVED** [review]

**Pull request merged**
