### PR TITLE
Use coverage in GitHub actions

### PR DESCRIPTION
**Pull request by Fagtoy**
Added a new job to GitHub actions, so for now a new coverage badge will be generated on every push. Badge itself looks like this:
image

### CODE REVIEW

**Review by SlavomirMazurPantheon — APPROVED** [review]

**Review by richardzilincikPantheon — COMMENTED** [review]
This is nice, but it doesn't give as much detail as the image. Could we add `coverate report` to the test job so we can view the detailed information in the log?

**Comment by richardzilincikPantheon** [comment]
Well I did see [this](https://github.com/marketplace/actions/code-coverage-summary) that I think should work with the file produced by `coverage xml`, but it's probably true that this info is only useful to developers, so I'd be fine with just having `coverage report` in the action.

**Comment by richardzilincikPantheon** [comment]
Or maybe a slightly more convenient way be to include the output of `coverage report` in a comment on the PR, but I'm not sure how much work that would be or if it's worth the extra effort.

**Comment by richardzilincikPantheon** [comment]
> So, do we need the report or a badge is enough?

The badge is enough for the readme. We don't need a full report committed to the repository. What I'm trying to say is if we just added the line `coverage report` to the end of test job, we'd be able to see the output along side the test results, so it would show up [here](https://github.com/YangCatalog/sdo_analysis/actions/runs/3393552825/jobs/5641018287). I think that would be useful.

**Comment by SlavomirMazurPantheon** [comment]
Badge for README.md and coverage report in Github Actions run - as an information for us developers - would be sufficient without need of change the README.md manually every time.

**Comment by Fagtoy** [comment]
@SlavomirMazurPantheon @richardzilincikPantheon For now there will be a comment on every PR with a full coverage report like [here](https://github.com/Fagtoy/sdo_analysis/pull/7#issuecomment-1307028382), so there's no need to check coverage report in GitHub actions manually. Such a comment is not generated for this PR because the ```Post coverage comment``` workflow can be triggered only if the workflow file is on the default branch (develop branch in our case), so if this PR is merged then I can open another one to test generation of the report

**Pull request merged**
