### PR TITLE
Pypy

### PR DESCRIPTION
**Pull request by richardzilincikPantheon**
In my testing, pyang has up to 2x better performance when running
under pypy. I've also seen a RAM usage decrease of about 10%.
If pyang runs faster, when runYANGgenericstats.sh runs, fewer
pyang processes will be running at once, resulting in lower total
RAM usage.

### CODE REVIEW

**Comment by SlavomirMazurPantheon** [comment]
1. Is there any difference between using `python:3.9` and `python:3.9-bullseye` images?
    - It would be best if exactly the same versions of the base image were used everywhere (backend, yangre, sdo-analysis)
2. I am getting following errors while running cronjob - running pyang command:
```
/usr/bin/pypy3: can't open file /usr/bin/pyang: [Errno 2] No such file or directory
```
Is there something wrong with my environment or there is some problem?

**Comment by richardzilincikPantheon** [comment]
When the next version if Debian is marked as stable, the `python:3.9` image will be updated to be based on the new release. This could be a problem if the names of any of the packages we use got changed, so it's better to specify the Debian release as well. We should probably do this with the rest of our images based on the python images as well.
I'll have a look at the cronjob issue.

**Comment by richardzilincikPantheon** [comment]
> 1. Is there any difference between using `python:3.9` and `python:3.9-bullseye` images?

So to answer the question, currently both tags refer to the same image, but this would change with a new Debian release.

**Comment by richardzilincikPantheon** [comment]
I got a different but related error.
```
/sdo_analysis/bin/runIETFstats.sh: line 130: /usr/bin/pyang: No such file or directory
```
I think this is because of an incorrect `yangcatalog.conf`. The example configuration sets
```
pyang-exec=/usr/bin/pyang
```
while pyang is actually installed at `/usr/local/bin/pyang`.
Storing this option in the config file might be unnecessary, as we can always retrieve the location with `which pyang` as long as it's somewhere in `PATH`.

**Comment by SlavomirMazurPantheon** [comment]
It is possible that after changing the base Docker image, pyang is installed elsewhere - moved from `/usr/bin/pyang` to `/usr/local/bin/pyang`

**Comment by richardzilincikPantheon** [comment]
Ah, I didn't think of that, yes that's probably it.

**Review by SlavomirMazurPantheon — APPROVED** [review]

**Pull request merged**
